name: Sum
description: Sum

inputs:
  x:
    default: 0
  y:
    default: 0

outputs:
  sum-result:
    value: ${{steps.sum.outputs.result}}
    description: sum result

runs:
  using: "composite" # must composite
  steps:
    - id: sum
      shell: bash
      run: echo "result=$((${{ inputs.x }} + ${{ inputs.y }}))" >> $GITHUB_OUTPUT
